### ISSUE TITLE
What does label_encoder mean

### ISSUE THREAD

**Issue by Frq-F** [hippolytelrm/teeth-3d-mesh-segmentation#8]
Hello, when I was learning your code, I didn't quite understand label_encoder. What does it mean and where did I get it from

**Comment by hippolytemayard** [comment]
Hello, thank you for your message. 
The label_encoder json file, is a mapping file, that allows mapping between labels and tooth numbers. 
I will change the naming, as it seems to be confusion.

**Comment by ds-seungwan** [comment]
Hello, I have two questions. Firstly, I'm curious about the source of the data annotation tool. Secondly, is it possible to receive the code for converting .obj and .json files into .vtp files?
